# Generated by Django 4.2.16 on 2024-12-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_meal_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance covered (e.g., km or miles)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='time',
            field=models.DurationField(blank=True, help_text='Time spent (e.g., HH:MM:SS)', null=True),
        ),
    ]
